title: Jing Niu
tagline: I am a quantative Marketing researcher in the University of Liverpool Management School (ULMS)
logo: /assets/img/picture-JING NIU.png
description: A quantative Marketing researcher in the University of Liverpool Management School (ULMS)
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
