title: Jing Niu
tagline: I am Phd candidate majoring quantative Marketing at HEC Paris 
logo: /assets/img/profile10.png
description: Phd candidate majoring quantative Marketing at HEC Paris 
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
