title: Jeremy Z Yang
tagline: Jeremy Z Yang. MIT Sloan School of Management.
logo: /assets/img/profile10.png
description: I'm a PhD candidate at MIT Sloan School of Management. 
Yoshow_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
